<a href="https://colab.research.google.com/github/yashika-git/Deep_Learning/blob/main/Einsum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Einsum is a replacement for
# Matrix mult
# element wise mult
# permutation
# dot product
# outer product
# specific summation
# batch matrix multiplication

# but it can be slow

# Free indices: indices specified in the output
# Summation indices: all other indices that appear in the input argument but not in the output specification
# np.einsum('ik, kj -> ij', A, B)  i,j are the free indices; k is the summation index

# Repeating letters in different inputs mean those values will be multiplied and those products will be the outputs
# Omitting a letter means that axis will be summed
# We can return the unsummed axis in any order 

In [7]:
import torch
x = torch.rand((2,3))
x

tensor([[0.0351, 0.1676, 0.7132],
        [0.9975, 0.6175, 0.9872]])

In [8]:
# permutation of tensors
torch.einsum('ij -> ji', x)  

tensor([[0.0351, 0.9975],
        [0.1676, 0.6175],
        [0.7132, 0.9872]])

In [9]:
# summation
torch.einsum('ij ->', x)

tensor(3.5181)

In [10]:
# column sum
torch.einsum('ij -> j', x)

tensor([1.0326, 0.7851, 1.7004])

In [11]:
# row sum
torch.einsum('ij -> i', x)

tensor([0.9159, 2.6022])

In [15]:
# matrix-vector multiplication
v = torch.rand((1, 3))
torch.einsum('ij, kj -> ik', x, v)

tensor([[0.3771],
        [1.5684]])

In [16]:
# matrix-matrix multiplication
# x.mm(x.t())
torch.einsum('ij,kj->ik', x, x)

tensor([[0.5380, 0.8426],
        [0.8426, 2.3509]])

In [17]:
# Dot product first row with first row of matrix
torch.einsum('i, i -> ', x[0], x[0])

tensor(0.5380)

In [18]:
# Dot product with matrix
torch.einsum('ij, ij ->', x, x)

tensor(2.8889)

In [19]:
# Hadmard Product (Element-wise multiplication)
torch.einsum('ij, ij -> ij', x, x)

tensor([[0.0012, 0.0281, 0.5086],
        [0.9951, 0.3813, 0.9746]])

In [20]:
# Outer product
a = torch.rand((3))
b = torch.rand((5))
torch.einsum('i, j -> ij', a, b)

tensor([[0.3832, 0.3779, 0.6246, 0.0813, 0.1030],
        [0.1362, 0.1343, 0.2221, 0.0289, 0.0366],
        [0.2626, 0.2590, 0.4281, 0.0557, 0.0706]])

In [21]:
# Batch matrix multiplication
a = torch.rand((3, 2, 5))
b = torch.rand((3, 5, 3))
torch.einsum('ijk, ikl -> ijl', a, b)

tensor([[[1.1196, 1.4078, 1.2437],
         [0.7102, 0.9587, 1.2213]],

        [[1.8401, 2.1103, 2.2985],
         [0.8381, 1.0935, 1.5373]],

        [[0.9451, 0.7147, 1.0670],
         [1.7880, 1.5639, 1.6733]]])

In [23]:
# Matrix Diagonal
x = torch.rand((3, 3))
print(x)
torch.einsum('ii -> i', x)

tensor([[0.0169, 0.9172, 0.5290],
        [0.5596, 0.6757, 0.8010],
        [0.9326, 0.2544, 0.5310]])


tensor([0.0169, 0.6757, 0.5310])

In [24]:
# Matrix Trace
torch.einsum('ii ->', x)

tensor(1.2236)

In [ ]:
# Reference: https://www.youtube.com/watch?v=pkVwUVEHmfI&list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz&index=38